{{- if and .Values.postgresql.external.enabled (not .Values.postgresql.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miot-calendar.fullname" . }}-db-credentials
  labels:
    {{- include "miot-calendar.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.external.password | b64enc | quote }}
{{- end }}
