global:
  imagePullSecrets: []
  labels: {}

miot-docs:
  enabled: false
  image:
    repository: ghcr.io/microboxlabs/miot-docs
    tag: ""

miot-app:
  enabled: true
  image:
    repository: ghcr.io/microboxlabs/miot-app
    tag: ""

miot-modulith:
  enabled: true
  image:
    repository: ghcr.io/microboxlabs/miot-srv
    tag: ""
