apiVersion: v2
name: modulariot
description: An umbrella Helm chart for ModularIoT platform - includes docs, website, and main app
type: application
version: 0.4.0
appVersion: "0.5.20"
keywords:
  - modulariot
  - iot
  - platform
  - umbrella
home: https://github.com/microboxlabs/modulariot
sources:
  - https://github.com/microboxlabs/modulariot
maintainers:
  - name: MicroboxLabs
    email: dev@microboxlabs.com
    url: https://microboxlabs.com

dependencies:
  - name: miot-docs
    version: "0.1.0"
    repository: "file://../miot-docs"
    condition: miot-docs.enabled
  - name: miot-web-site
    version: "0.1.0"
    repository: "file://../miot-web-site"
    condition: miot-web-site.enabled
  - name: miot-app
    version: "0.3.3"
    repository: "file://../miot-app"
    condition: miot-app.enabled
  - name: miot-modulith
    version: "0.5.0"
    repository: "file://../miot-modulith"
    condition: miot-modulith.enabled
  - name: miot-harness
    version: "0.4.0"
    repository: "file://../miot-harness"
    condition: miot-harness.enabled
