{{- if and (not .Values.auth.existingSecret) (or .Values.auth.secret .Values.auth.providers.google.enabled .Values.auth.providers.auth0.enabled) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miot-app.authSecretName" . }}
  labels:
    {{- include "miot-app.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.auth.secret }}
  auth-secret: {{ .Values.auth.secret | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.providers.google.enabled }}
  google-client-id: {{ .Values.auth.providers.google.clientId | b64enc | quote }}
  google-client-secret: {{ .Values.auth.providers.google.clientSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.auth.providers.auth0.enabled }}
  auth0-client-id: {{ .Values.auth.providers.auth0.clientId | b64enc | quote }}
  auth0-client-secret: {{ .Values.auth.providers.auth0.clientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
