apiVersion: v2
name: miot-app
description: A Helm chart for ModularIoT App - Main Next.js application with authentication and maps
type: application
version: 0.3.1
appVersion: "1.0.0"
keywords:
  - application
  - nextjs
  - auth
  - maps
  - modulariot
home: https://github.com/microboxlabs/modulariot
sources:
  - https://github.com/microboxlabs/modulariot
maintainers:
  - name: MicroboxLabs
    email: dev@microboxlabs.com
    url: https://microboxlabs.com
