apiVersion: v2
name: miot-web-site
description: A Helm chart for ModularIoT Website - Next.js marketing and landing pages
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - website
  - marketing
  - landing
  - nextjs
  - modulariot
home: https://github.com/microboxlabs/modulariot
sources:
  - https://github.com/microboxlabs/modulariot
maintainers:
  - name: MicroboxLabs
    email: dev@microboxlabs.com
    url: https://microboxlabs.com
