{{- if .Values.apisixRoute.enabled -}}
{{- $fullName := include "miot-modulith.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "miot-modulith.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ .Values.apisixRoute.ingressClassName }}
  http:
  {{- range .Values.apisixRoute.hosts }}
    - name: {{ .host | replace "." "-" }}
      match:
        hosts:
          - {{ .host }}
        paths:
          {{- toYaml .paths | nindent 10 }}
      backends:
        - serviceName: {{ $fullName }}
          servicePort: {{ $svcPort }}
      {{- with $.Values.apisixRoute.plugins }}
      plugins:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{- end }}
{{- end }}
