{{- if not .Values.postgresql.external.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miot-modulith.fullname" . }}-db-credentials
  labels:
    {{- include "miot-modulith.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgresql.external.password | b64enc | quote }}
{{- end }}
---
{{- if not .Values.oidc.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "miot-modulith.fullname" . }}-oidc-credentials
  labels:
    {{- include "miot-modulith.labels" . | nindent 4 }}
type: Opaque
data:
  client-secret: {{ .Values.oidc.clientSecret | b64enc | quote }}
{{- end }}
