name: Relase Helm Charts

run-name: ${{ github.actor }} is releasing {{ github.repository.name }} 🚀

on: [push, pull_request]

jobs:
  Release-Helm-Charts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"